name: Run linter and tests on merge
on:
  pull_request:
    branches: [ develop ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Install modules
        run: yarn
#     disabled until eslint issues can be cleaned up
#      - name: Run linter
#        run: yarn lint
      - name: Run tests with coverage
        run: yarn test --coverage